name: convert_structure_to_json
description: A package to convert project structure to json format.
version: 1.0.1
repository: https://github.com/beobanhbo/convert-structure-to-json

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  args: ^2.3.1
dev_dependencies:
  flutter_lints: ^1.0.0


executables:
  convert_structure: convert_structure_to_json
